---
sidebar: sidebar 
permalink: trident-concepts/intro.html 
keywords: product overview, astra trident 
summary: 'Il provisioning in Astra Trident prevede due fasi principali. La prima fase associa una classe di storage all"insieme di pool di storage di back-end adatti e si verifica come preparazione necessaria prima del provisioning. La seconda fase include la creazione stessa di un volume e richiede la scelta di un pool di storage tra quelli associati alla classe di storage del volume in sospeso.' 
---
= Introduzione ad Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident è un progetto open source completamente supportato, gestito da NetApp nell'ambito di link:https://docs.netapp.com/us-en/astra-family/intro-family.html["Famiglia di prodotti Astra"^]. È stato progettato per aiutare a soddisfare le richieste di persistenza delle applicazioni containerizzate utilizzando interfacce standard del settore, come Container Storage Interface (CSI).

Astra Trident si implementa nei cluster Kubernetes come pod e fornisce servizi di orchestrazione dello storage dinamico per i carichi di lavoro Kubernetes. Permette alle tue applicazioni containerizzate di consumare rapidamente e facilmente storage persistente dall'ampio portfolio di NetApp, che include ONTAP (AFF/FAS/Select/cloud/Amazon FSX per NetApp ONTAP), il software Element (NetApp HCI/SolidFire), oltre al servizio Azure NetApp Files, Cloud Volumes Service su Google Cloud e Cloud Volumes Service su AWS.

Astra Trident è anche una tecnologia di base per Astra di NetApp, che si occupa di protezione dei dati, disaster recovery, portabilità e casi di utilizzo della migrazione per i carichi di lavoro Kubernetes sfruttando la tecnologia di gestione dei dati leader del settore di NetApp per snapshot, backup, replica e cloning.



== Architetture cluster Kubernetes supportate

Astra Trident è supportato con le seguenti architetture Kubernetes:

[cols="3*"]
|===
| Kubernetes architetture di cluster | Supportato | Installazione predefinita 


| Singolo master, calcolo | Sì  a| 
Sì



| Master multipli, calcolo | Sì  a| 
Sì



| Master, `etcd`calcolo | Sì  a| 
Sì



| Master, infrastruttura, calcolo | Sì  a| 
Sì

|===


== Che cos'è Astra?

Astra semplifica la gestione, la protezione e lo spostamento dei carichi di lavoro containerizzati ricchi di dati eseguiti su Kubernetes all'interno e tra cloud pubblici e on-premise. Astra fornisce e fornisce storage container persistente utilizzando Astra Trident del comprovato e esteso portfolio di storage NetApp nel cloud pubblico e on-premise. Offre inoltre una serie completa di funzionalità avanzate di gestione dei dati applicative, come snapshot, backup e ripristino, log di attività e cloning attivo per la protezione dei dati, disaster recovery/data, audit dei dati e casi di utilizzo della migrazione per i carichi di lavoro Kubernetes.

Dai un'occhiata alla documentazione di Astra per iniziare subito. Puoi iscriverti oggi stesso per una prova gratuita nella pagina Astra.

* https://docs.netapp.com/us-en/astra/get-started/intro.html["Introduzione al servizio di controllo Astra"^]
* https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html["Inizia subito con Astra API"^]
* https://docs.netapp.com/us-en/astra-control-center/concepts/intro.html["Scopri di più su Astra Control Center"^]

